services:
  - type: web
    name: allcoast
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/status
    autoDeploy: true
